---
title: "The Story of McDonalds"
execute: 
  eval: false
  echo: false
engine: knitr
---

Hey there, data explorer! Let's embark on a journey through the golden arches and dive into the fascinating world of McDonald's. Buckle up, because we're about to unravel some intriguing insights!

Here, we have a map of all the McDonalds around the world!

## McDonald's All Around the World (As of 2022)

<iframe height="560" width="100%" frameborder="no" src=" https://kyrawu.shinyapps.io/McDWorldMap/">

</iframe>

### McDonald's Density Hot Spots

With the 'McDonald's Outlets per Million Residents' toggle activated, a clear trend emerges -- the density of McDonald's locations is notably high in the US, Canada, Europe, and Australia. This concentration indicates a strong presence in these regions relative to their populations. However, the story takes an interesting turn when we examine countries with the least dense McDonald's to Population ratio, such as Peru, Egypt, and India.

### The Golden Arches and GDP 

When toggling on 'GDP per Capita', you may notice that there is barely any changes in colour, save a few countries like China and some regions in Europe etc. The graph shows that there is a positive correlation between GDP per capita and the number of McDonald's outlets in a country. This is consistent with the findings from the first graph, which showed that wealthier countries tend to have more McDonald's outlets per million residents.

This correlation can be explained by a number of factors, including:

-   **Wealthier countries tend to have more urbanization and higher levels of disposable income.** This creates a larger market for fast food restaurants like McDonald's.

-   **Wealthier countries also tend to have more foreign direct investment.** McDonald's is one of the world's largest foreign direct investors, and it has a long history of expanding into new markets.

-   **Some people argue that McDonald's is a symbol of Western culture and globalization.** Wealthier countries are more likely to be exposed to Western culture and globalization, and this may lead to a greater demand for McDonald's restaurants.

### Exploring Disparities 

The countries with lower McDonald's density often share common characteristics. Many are classified as developing nations, where disposable income is limited, and supply chains pose considerable challenges. Additionally, some countries attribute their low McDonald's density to political reasons, a small local population, or simply a lack of affinity for American fast-food burgers.

### Africa: A Unique Landscape

Zooming in on Africa, a continent seemingly devoid of McDonald's presence, we uncover a myriad of factors influencing this phenomenon.

| **Factors**             | **Implications**                                                                                                                                                                                                                                       |
|------------------|------------------------------------------------------|
| Economic Challenges     | Africa's diverse economic landscape poses challenges like poverty, political instability, and underdeveloped infrastructure. These hurdles can hinder McDonald's efforts to establish profitable operations in certain regions.                        |
| Cultural Diversity      | Africa's rich culinary heritage presents a complex challenge. While McDonald's adapts menus to local tastes, achieving a balance between global consistency and diverse local preferences becomes intricate in a continent with such culinary variety. |
| Supply Chain Struggles  | McDonald's stringent quality standards rely on efficient supply chains. Inadequate infrastructure, including transportation and logistics, in Africa can impede the reliable supply of ingredients, affecting the company's quality standards.         |
| Fierce Competition      | The fast-food industry in Africa is fiercely competitive, with local and international chains vying for market share. Entering this market demands careful research and an effective competitive strategy.                                             |
| Regulatory Complexities | Different African countries have varying regulations for foreign businesses. Navigating these diverse regulatory frameworks can be time-consuming and financially burdensome for McDonald's.                                                           |

## The Big Mac Price

<iframe height="625" width="100%" frameborder="no" src="https://kyrawu.shinyapps.io/BigMacPrice/">

</iframe>

## What you should eat at McDonald's

<iframe height="600" width="100%" frameborder="no" src="https://kyrawu.shinyapps.io/McDNutrition/">

</iframe>

If you would like to read more about the journey of crafting this page, check it out here
