---
title: "McDonald's :^)"
author: "Kyra Wu"
date: "`r Sys.Date()`"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```
## Reading in data

```{r}
setwd("/Users/ethan/Documents/Documents/Y3S1/kyra/APAC mcd menus")
df = read_csv("[2023-11-03 07_37_15] mcd-api-in.csv")
df = df %>% mutate(`Price (USD)` = round(`Price (INR)`*0.0120268, 2) ) #fixing calculation error in data
write_csv(df, "[2023-11-03 07_37_15] mcd-api-in.csv")
```

##apac_menus
```{r}
setwd("/Users/ethan/Documents/Documents/Y3S1/kyra")
bmi = read_csv("BigmacPrice.csv")
outlets = read_csv("most mcdonalds countries 2022 - Sheet1.csv")
nutrition = read_xlsx("pffy-data-mcdonalds-nutrition-facts.xlsx", sheet = 1)
setwd("/Users/ethan/Documents/Documents/Y3S1/kyra/APAC mcd menus")
csv_files=list.files(pattern = "*.csv$")
apac_menus = NULL

for (file in csv_files) {
  df <- read.csv(file, stringsAsFactors = FALSE)
  required_columns <- c("Territory", "Menu.Item", "Price..USD.", "Category")
  # Check if the "Menu" column exists, if not, create it with NA values
  if(!("Menu" %in% names(df))) {
    df$Menu <- NA  # Add the Menu column with NA values
  }
  df <- df[, c(required_columns, "Menu"), drop = FALSE]
  # Bind this dataframe to the merged dataframe
  if (is.null(apac_menus)) {
    apac_menus <- df
  } else {
    apac_menus <- rbind(apac_menus, df)
  }
}
setwd("/Users/ethan/Documents/Documents/Y3S1/kyra")
names(apac_menus) = c("territory", "menu item", "price", "category", "menu")
write_csv(apac_menus, "apac_menus.csv")

```

##outlets data
```{r}
#install.packages("countrycode")
#install.packages("maps")
library(countrycode)
library(maps)

# Add country code
outlets <- outlets %>%
  mutate(country_code = countrycode(Country, "country.name", "iso3c"),
         outlets_per_mil = `Number of Restaurants per Million Population`,
         num_outlets = `Number of Restaurants`) %>%
  select(-`Number of Restaurants per Million Population`, -`Number of Restaurants`)

# Create a lookup table for latitudes and longitudes
world_cities <- maps::world.cities %>%
  distinct(country.etc, lat, long) %>%
  rename(Country = country.etc)

# Join with your data
outlets <- left_join(outlets, world_cities, by = "Country")


# Write updated dataset
write_csv(outlets, "outlets.csv")
```






